[package]
name = "year-2016-day-22"
version = "0.1.0"
authors = ["Eric Petersen <eric@huskers.unl.edu>"]
edition = "2021"

[dependencies]
common = { path = "../../common" }
lazy_static = "1"
itertools = "0.10"
regex = "1"
